
# JWT Configuration
jwt:
  secret: 2?Q:mba;7mvN[^0=Ixw54z@YOiySC!TqGF)-20tOL`*qs^AlK_|gYoS;ah0r2Oj
  expiration: 900_000 # 15 minutes
  issuer: 'Obsidi Academy'
  audience: WeatherApp
  prefix: 'Bearer '
  excluded.urls: > 
    /user/login,
    /user/signup,
    /user/reset/*,
    /test/**,
    /actuator/**,
    /error,
    
# Open Weather API Configuration  
api:
  key: 44120226c46f68b253f8a0e1ba442f0c
  base:
    url: https://api.openweathermap.org/data/2.5/weather

# Client Configuration  
client:
  url: http://localhost:3000
  email:
    verify: 
      param: verify
      expiration: 86_400_000 # 24 hours
    reset: 
      param: reset
      expiration: 600_000 # 10 minutes 