name: React, Java CI with Node, Maven and JUnit

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and test backend with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
          TZ: America/Toronto
        run: mvn -B clean test --file WeatherApp-Backend/weatherApp/pom.xml
          
      - name: Install Node.js and npm for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install dependencies and build frontend
        run: |
          cd WeatherApp-FrontEnd/weather-app-frontend/
          npm install
          CI=false && npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: WeatherApp-FrontEnd/weather-app-frontend/build
          
      - name: Publish JUnit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "**/surefire-reports/TEST-*.xml"
          format: junit
